### ISSUE TITLE
how to use to_list?

### ISSUE THREAD

**Issue by xiandong79** [bmoscon/orderbook#21]
```
Traceback (most recent call last):
  File "/home/ubuntu/.pycharm_helpers/pydev/_pydevd_bundle/pydevd_exec2.py", line 3, in Exec
    exec(exp, global_vars, local_vars)
  File "<input>", line 1, in <module>
AttributeError: 'order_book.SortedDict' object has no attribute 'to_list'
self.bid.to_list()
Traceback (most recent call last):
  File "/home/ubuntu/.pycharm_helpers/pydev/_pydevd_bundle/pydevd_exec2.py", line 3, in Exec
    exec(exp, global_vars, local_vars)
  File "<input>", line 1, in <module>
AttributeError: 'order_book.SortedDict' object has no attribute 'to_list'
```

could you add an example in **Basic Usage** section in README ?

**Comment by bmoscon** [comment]
added. when you tried it I don't believe the release had been published that included the `to_list` method
